[package]
name = "flashcards"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-watch = "8.5.2"
derive_builder = "0.20.0"
derive_more = "0.99.17"
pretty_assertions = "1.4.0"
serde = "1.0.197"
